---
title: "Rene Ingersoll's Resume"
author: Lijia Yu
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

Aside
================================================================================



Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> ringersoll2@unl.edu
- <i class="fa fa-github"></i> [github.com/reingersoll](https://github.com/reingersoll)
- <i class="fa fa-phone"></i> +1 000-0000
- For more information, please contact me via email.


Skills {#skills}
--------------------------------------------------------------------------------

- Software Proficiency in: ArcGIS Products, QGIS, ERDAS IMAGINE, ENVI, Microsoft Office, Programming in Python and R.

- Summary of Skills: Excellent Analystical Skills, Cooperative Team Member, Extremely Organized, Quick Learner, Challenge Embracer



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.



Main
================================================================================

Rene Ingersoll {#title}
--------------------------------------------------------------------------------

### Career Objective

Currently, I am continuing to pursue an education in Geography and GIS as I attend UNL for my masters. I have a history of work, academic and extracurricular excellence. I have a passion to learn about the world and the diversity of people living on it and interacting with it. I hope to encompass my passion with my knowledge gained through classes and research to pursue a future career using GIS to better my community.


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### University of Nebraska Lincoln

Programming, Chemistry, General Studies

Lincoln, NE

2015-2016

No degree obtained

### University of Nebraska Kearney

B.A. Geography, Japanese		

Kearney, NE

2016-2020

### University of Nebraska Lincoln

M.A. Geography, Statistics Minor 

Lincoln, NE

2020 - present


Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

### Graduate Research Assistant

University of Nebraska Lincoln

Lincoln, NE

2021 - present

- Flood Vulnerability Index
  -	Defining areas with high vulnerability to the impacts of floods in Nebraska. Data is based on physical geography and demographics of the population. 
- Water Governance Database
  - Creating a database of each water governance institutions in the United States by state.
  
### Undergraduate Research Assistant

University of Nebraska Kearney

Kearney, NE

2019-2020

-	Creating a database to describe and analyze the distributions of conflict and collaboration along the Platte River.

### GIS and Market Analysis of an In-Home Health Care Center 

University of Nebraska Kearney

Kearney, NE

2019

-	This study was conducted as a class project, where we looked at clients of the business and their relation to its location to determine where potential growth could be found in the area. The business has since utilized our results and is promoting themselves in the areas we identified.
-	Featured a poster and verbal presentation at Nebraska GIS Symposium
-	Presented poster at AAG Great Plains and Rocky Mountains Regional Conference	.
  

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### GIS Intern

Nebraska Department of Transportation

Lincoln, NE

2021 - present

::: concise
- Archive previous Right of Way purchases
- Geo-reference Right of Way purchases
- Update and maintain web map for Right of Way Division
:::

### GIS Student Intership

University of Nebraska Lincoln

Lincoln, NE

2019

::: concise
- Worked for the university on various projects with CLAMIT and ENREC centers
- Created an interactive soils map that described the soil type in each designated field and the percent it made up.
- Created a story map that described examples of remote sensing for the researchers to use and assist with their work
:::


Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Teacher Assistant

Teaching assistant for physical geography labs.

Lincoln, NE

2020-2021



Selected Publications and Posters {data-icon=file}
--------------------------------------------------------------------------------

### Analysis of the Spatial Arrangement of Shinto Shrines
Poster for 2018 UNK Research Day.

Kearney, Nebraska

2018

**Rene Ingersoll**


 
